/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Backend */

#ifndef _Included_Backend
#define _Included_Backend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Backend
 * Method:    getBoardCopy
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_Backend_getBoardCopy
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getTextLost
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getTextLost
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getTextWon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getTextWon
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getTextTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getTextTitle
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getHeaderHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getHeaderHeight
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellSize
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellMargin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellMargin
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getWindowMargin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getWindowMargin
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellBitMine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellBitMine
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellBitFlag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellBitFlag
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellBitClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellBitClear
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getFlagPNGPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getFlagPNGPath
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getStateLost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getStateLost
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getStateWon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getStateWon
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    gameGetState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_gameGetState
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    gameGetSurroundingMines
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Backend_gameGetSurroundingMines
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Backend
 * Method:    gameGetFlagsLeft
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_gameGetFlagsLeft
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    gameClearCell
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Backend_gameClearCell
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Backend
 * Method:    gameFlagCell
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Backend_gameFlagCell
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
