/*

    arfminesweeper: Cross-plataform multi-frontend game
    Copyright (C) 2023 arf20 (Ángel Ruiz Fernandez)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

    backend.c: Java JNI native methods

*/

#include <stdlib.h>

#include "Backend.h" /* autogenerated by javac */
#include <common/frontconf.h>

#include "javaawt.h"


JNIEXPORT jintArray JNICALL 
Java_Backend_getBoardCopy(JNIEnv *env, jobject this) {
    int size = javaawt_getsize();

    jintArray jni_board_copy = (*env)->NewIntArray(env, size * size);
    (*env)->SetIntArrayRegion(env, jni_board_copy, 0, size * size,
        javaawt_getboard());

    return jni_board_copy;
}

JNIEXPORT jint JNICALL
Java_Backend_getHeaderHeight(JNIEnv *env, jobject this) {
    return HEADER_HEIGHT;
}

JNIEXPORT jint JNICALL
Java_Backend_getCellSize(JNIEnv *env, jobject this) {
    return CELL_SIZE;
}

JNIEXPORT jint JNICALL
Java_Backend_getCellMargin(JNIEnv *env, jobject this) {
    return CELL_MARGIN;
}

JNIEXPORT jint JNICALL
Java_Backend_getWindowMargin(JNIEnv *env, jobject this) {
    return W_MARGIN;
}

JNIEXPORT jstring JNICALL
Java_Backend_getTextLost(JNIEnv *env, jobject this) {
    jstring jni_string_copy = (*env)->NewStringUTF(env, TXT_LOST);
}

JNIEXPORT jstring JNICALL
Java_Backend_getTextWon(JNIEnv *env, jobject this) {
    jstring jni_string_copy = (*env)->NewStringUTF(env, TXT_WON);
}

JNIEXPORT jstring JNICALL
Java_Backend_getTextTitle(JNIEnv *env, jobject this) {
    jstring jni_string_copy = (*env)->NewStringUTF(env, TXT_TITLE);
}


