/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Backend */

#ifndef _Included_Backend
#define _Included_Backend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Backend
 * Method:    getBoardCopy
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_Backend_getBoardCopy
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getTextLost
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getTextLost
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getTextWon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getTextWon
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getTextTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Backend_getTextTitle
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getHeaderHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getHeaderHeight
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellSize
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getCellMargin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getCellMargin
  (JNIEnv *, jobject);

/*
 * Class:     Backend
 * Method:    getWindowMargin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Backend_getWindowMargin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
