/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class awt_frame */

#ifndef _Included_awt_frame
#define _Included_awt_frame
#ifdef __cplusplus
extern "C" {
#endif
#undef awt_frame_FOCUS_TRAVERSABLE_UNKNOWN
#define awt_frame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef awt_frame_FOCUS_TRAVERSABLE_DEFAULT
#define awt_frame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef awt_frame_FOCUS_TRAVERSABLE_SET
#define awt_frame_FOCUS_TRAVERSABLE_SET 2L
#undef awt_frame_TOP_ALIGNMENT
#define awt_frame_TOP_ALIGNMENT 0.0f
#undef awt_frame_CENTER_ALIGNMENT
#define awt_frame_CENTER_ALIGNMENT 0.5f
#undef awt_frame_BOTTOM_ALIGNMENT
#define awt_frame_BOTTOM_ALIGNMENT 1.0f
#undef awt_frame_LEFT_ALIGNMENT
#define awt_frame_LEFT_ALIGNMENT 0.0f
#undef awt_frame_RIGHT_ALIGNMENT
#define awt_frame_RIGHT_ALIGNMENT 1.0f
#undef awt_frame_serialVersionUID
#define awt_frame_serialVersionUID -7644114512714619750LL
#undef awt_frame_serialVersionUID
#define awt_frame_serialVersionUID 4613797578919906343LL
#undef awt_frame_INCLUDE_SELF
#define awt_frame_INCLUDE_SELF 1L
#undef awt_frame_SEARCH_HEAVYWEIGHTS
#define awt_frame_SEARCH_HEAVYWEIGHTS 1L
#undef awt_frame_OPENED
#define awt_frame_OPENED 1L
#undef awt_frame_serialVersionUID
#define awt_frame_serialVersionUID 4497834738069338734LL
#undef awt_frame_DEFAULT_CURSOR
#define awt_frame_DEFAULT_CURSOR 0L
#undef awt_frame_CROSSHAIR_CURSOR
#define awt_frame_CROSSHAIR_CURSOR 1L
#undef awt_frame_TEXT_CURSOR
#define awt_frame_TEXT_CURSOR 2L
#undef awt_frame_WAIT_CURSOR
#define awt_frame_WAIT_CURSOR 3L
#undef awt_frame_SW_RESIZE_CURSOR
#define awt_frame_SW_RESIZE_CURSOR 4L
#undef awt_frame_SE_RESIZE_CURSOR
#define awt_frame_SE_RESIZE_CURSOR 5L
#undef awt_frame_NW_RESIZE_CURSOR
#define awt_frame_NW_RESIZE_CURSOR 6L
#undef awt_frame_NE_RESIZE_CURSOR
#define awt_frame_NE_RESIZE_CURSOR 7L
#undef awt_frame_N_RESIZE_CURSOR
#define awt_frame_N_RESIZE_CURSOR 8L
#undef awt_frame_S_RESIZE_CURSOR
#define awt_frame_S_RESIZE_CURSOR 9L
#undef awt_frame_W_RESIZE_CURSOR
#define awt_frame_W_RESIZE_CURSOR 10L
#undef awt_frame_E_RESIZE_CURSOR
#define awt_frame_E_RESIZE_CURSOR 11L
#undef awt_frame_HAND_CURSOR
#define awt_frame_HAND_CURSOR 12L
#undef awt_frame_MOVE_CURSOR
#define awt_frame_MOVE_CURSOR 13L
#undef awt_frame_NORMAL
#define awt_frame_NORMAL 0L
#undef awt_frame_ICONIFIED
#define awt_frame_ICONIFIED 1L
#undef awt_frame_MAXIMIZED_HORIZ
#define awt_frame_MAXIMIZED_HORIZ 2L
#undef awt_frame_MAXIMIZED_VERT
#define awt_frame_MAXIMIZED_VERT 4L
#undef awt_frame_MAXIMIZED_BOTH
#define awt_frame_MAXIMIZED_BOTH 6L
#undef awt_frame_serialVersionUID
#define awt_frame_serialVersionUID 2673458971256075116LL
#undef awt_frame_HEADER_HEIGHT
#define awt_frame_HEADER_HEIGHT 60L
#undef awt_frame_CELL_SIZE
#define awt_frame_CELL_SIZE 20L
#undef awt_frame_CELL_MARGIN
#define awt_frame_CELL_MARGIN 2L
#undef awt_frame_W_MARGIN
#define awt_frame_W_MARGIN 5L
/*
 * Class:     awt_frame
 * Method:    getBoardCopy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_awt_1frame_getBoardCopy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
