if (MODULE_ALL)
    set(MODULE_ANSI TRUE)
    set(MODULE_CONSOLE TRUE)
    set(MODULE_CURSES TRUE)
    set(MODULE_D2D TRUE)
    set(MODULE_DRMFB TRUE)
    set(MODULE_FBDEV TRUE)
    set(MODULE_FLTK TRUE)
    set(MODULE_GDI TRUE)
    set(MODULE_GL11 TRUE)
    set(MODULE_GL33 TRUE)
    set(MODULE_GL3D TRUE)
    set(MODULE_GLX TRUE)
    set(MODULE_GTK3 TRUE)
    set(MODULE_HTTPD TRUE)
    set(MODULE_AWT TRUE)
    set(MODULE_MOTIF TRUE)
    set(MODULE_QT5 TRUE)
    set(MODULE_SDL1 TRUE)
    set(MODULE_SDL2 TRUE)
    set(MODULE_SWING TRUE)
    set(MODULE_VK TRUE)
    set(MODULE_VT100 TRUE)
    set(MODULE_WAYLAND TRUE)
    set(MODULE_WIN32 TRUE)
    set(MODULE_WXWIDGETS TRUE)
    set(MODULE_XAW TRUE)
    set(MODULE_XCB TRUE)
    set(MODULE_XFORMS TRUE)
    set(MODULE_XLIB TRUE)
    set(MODULE_SDL3 TRUE)
endif()

if (NOT NO_STATIC)
    set(STATIC_ANSI TRUE)
    set(STATIC_CONSOLE TRUE)
    set(STATIC_CURSES TRUE)
    set(STATIC_D2D TRUE)
    set(STATIC_DRMFB TRUE)
    set(STATIC_FBDEV TRUE)
    set(STATIC_FLTK TRUE)
    set(STATIC_GDI TRUE)
    set(STATIC_GL11 TRUE)
    set(STATIC_GL33 TRUE)
    set(STATIC_GL3D TRUE)
    set(STATIC_GLX TRUE)
    set(STATIC_GTK3 TRUE)
    set(STATIC_HTTPD TRUE)
    set(STATIC_AWT TRUE)
    set(STATIC_MOTIF TRUE)
    set(STATIC_QT5 TRUE)
    set(STATIC_SDL1 FALSE)
    set(STATIC_SDL2 FALSE)
    set(STATIC_SWING TRUE)
    set(STATIC_VK TRUE)
    set(STATIC_VT100 TRUE)
    set(STATIC_WAYLAND TRUE)
    set(STATIC_WIN32 TRUE)
    set(STATIC_WXWIDGETS TRUE)
    set(STATIC_XAW TRUE)
    set(STATIC_XCB TRUE)
    set(STATIC_XFORMS TRUE)
    set(STATIC_XLIB TRUE)
    set(STATIC_SDL3 TRUE)
endif()

# check conflicts
if ((STATIC_SDL2 AND STATIC_SDL3) OR (STATIC_SDL1 AND STATIC_SDL3) OR (STATIC_SDL1 AND STATIC_SDL2))
    message(FATAL_ERROR "SDLs are mutually exclusive on static builds")
endif()

# common targets
add_subdirectory("common")

add_subdirectory("awt")
add_subdirectory("qt5")
add_subdirectory("xcb")
add_subdirectory("gl33")
add_subdirectory("gl3d")
add_subdirectory("gtk3")
add_subdirectory("gl11")
add_subdirectory("fltk")
add_subdirectory("d2d")
add_subdirectory("sdl1")
add_subdirectory("xforms")
add_subdirectory("vt100")
add_subdirectory("console")
add_subdirectory("vk")
add_subdirectory("fbdev")
add_subdirectory("motif")
add_subdirectory("win32")
add_subdirectory("wayland")
add_subdirectory("ansi")
add_subdirectory("sdl2")
add_subdirectory("xaw")
add_subdirectory("glx")
add_subdirectory("gdi")
add_subdirectory("curses")
add_subdirectory("xlib")
add_subdirectory("httpd")
add_subdirectory("drmfb")
add_subdirectory("wxwidgets")
add_subdirectory("swing")
add_subdirectory("sdl3")

