/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArfBackend */

#ifndef _Included_ArfBackend
#define _Included_ArfBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArfBackend
 * Method:    getBoardCopy
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ArfBackend_getBoardCopy
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    gameGetSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_gameGetSize
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    gameGetState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_gameGetState
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    gameGetSurroundingMines
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_gameGetSurroundingMines
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ArfBackend
 * Method:    gameGetFlagsLeft
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_gameGetFlagsLeft
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    gameClearCell
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ArfBackend_gameClearCell
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ArfBackend
 * Method:    gameFlagCell
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ArfBackend_gameFlagCell
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ArfBackend
 * Method:    getTextLost
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArfBackend_getTextLost
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getTextWon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArfBackend_getTextWon
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getTextTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArfBackend_getTextTitle
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getHeaderHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getHeaderHeight
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getCellSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getCellSize
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getCellMargin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getCellMargin
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getWindowMargin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getWindowMargin
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getCellBitMine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getCellBitMine
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getCellBitFlag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getCellBitFlag
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getCellBitClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getCellBitClear
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getFlagPNGPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArfBackend_getFlagPNGPath
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getStateLost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getStateLost
  (JNIEnv *, jobject);

/*
 * Class:     ArfBackend
 * Method:    getStateWon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ArfBackend_getStateWon
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
