name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential nasm cmake rsync libx11-dev libxcb1-dev libwayland-dev libforms-dev libmotif-dev libxaw7-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libgl-dev freeglut3-dev libglfw3-dev libvulkan-dev glslc libgtk-3-dev qtbase5-dev libdrm-dev gnu-efi binutils-mingw-w64 gcc-mingw-w64 xorriso mtools

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --verbose

    - name: Package
      run: cpack --config build/CPackConfig.cmake --verbose -G "TGZ;DEB"

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: arfminesweeper-linux-deb
        path: ./*.deb

    - name: Upload TGZ artifact
      uses: actions/upload-artifact@v4
      with:
        name: arfminesweeper-linux-tarball
        path: ./*.tar.gz

    - name: Upload deb to repo
      run: RSYNC_PASSWORD=${{secrets.RSYNC_REPO_PASS}} rsync -avz ./*.deb rsync://debupload@arf20.com/debupload/pool/contrib/
