name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential cmake libx11-dev libxcb1-dev libwayland-dev libforms-dev libmotif-dev libxaw7-dev libsdl2-dev libsdl1.2-dev libgl-dev freeglut3-dev libglfw3-dev libvulkan-dev libgtk-3-dev qtbase5-dev libdrm-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --verbose

    - name: Package
      run: cpack --config build/CPackConfig.cmake --verbose -G "TGZ;DEB"

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: arfminesweeper-linux-deb
        path: ./*.deb

    - name: Upload TGZ artifact
      uses: actions/upload-artifact@v4
      with:
        name: arfminesweeper-linux-tarball
        path: ./*.tar.gz
